package com.megalife.ime.feature

/**
 * Predicts emoji based on typed keywords.
 * Supports both English and Hebrew keyword mappings.
 * Respects KosherEmojiFilter to exclude inappropriate emoji.
 */
class EmojiPredictor(private val kosherFilter: KosherEmojiFilter?) {

    /**
     * Map of keywords to emoji suggestions.
     * Contains 100+ mappings covering English and Hebrew keywords.
     */
    private val keywordMap: Map<String, List<String>> = mapOf(
        // ===== ENGLISH - Emotions & Expressions =====
        "happy" to listOf("😊", "😄", "🙂", "😁"),
        "sad" to listOf("😢", "😞", "😔", "🥺"),
        "love" to listOf("❤️", "😍", "💕", "🥰"),
        "laugh" to listOf("😂", "🤣", "😆"),
        "angry" to listOf("😠", "😡"),
        "smile" to listOf("😊", "🙂", "😄"),
        "cry" to listOf("😢", "😭", "🥲"),
        "wow" to listOf("😮", "🤯", "😲"),
        "cool" to listOf("😎", "🆒"),
        "wink" to listOf("😉", "😜"),
        "hug" to listOf("🤗", "🫂"),
        "shy" to listOf("😊", "🙈"),
        "bored" to listOf("😐", "😑", "🥱"),
        "tired" to listOf("😴", "🥱", "😪"),
        "confused" to listOf("😕", "🤔", "😵"),
        "nervous" to listOf("😰", "😬", "🥺"),
        "excited" to listOf("🤩", "🎉", "😆"),
        "surprised" to listOf("😮", "😲", "😳"),
        "worried" to listOf("😟", "😰", "😧"),
        "proud" to listOf("😊", "🏆", "💪"),
        "grateful" to listOf("🙏", "❤️", "😊"),
        "sorry" to listOf("😔", "🙏", "😢"),
        "embarrassed" to listOf("😳", "🙈", "😅"),

        // ===== ENGLISH - Gestures & Actions =====
        "ok" to listOf("👍", "👌", "✅"),
        "yes" to listOf("✅", "👍", "🙌"),
        "no" to listOf("❌", "👎", "🚫"),
        "thanks" to listOf("🙏", "❤️", "😊"),
        "thank" to listOf("🙏", "❤️", "😊"),
        "please" to listOf("🙏", "🥺"),
        "hello" to listOf("👋", "🙂", "✌️"),
        "hi" to listOf("👋", "🙂"),
        "bye" to listOf("👋", "✌️"),
        "goodbye" to listOf("👋", "✌️", "😢"),
        "welcome" to listOf("🙌", "👋", "😊"),
        "congrats" to listOf("🎉", "🥳", "👏"),
        "congratulations" to listOf("🎉", "🥳", "👏"),
        "clap" to listOf("👏", "🙌"),
        "wave" to listOf("👋", "✌️"),
        "point" to listOf("👆", "☝️", "👉"),
        "thumbsup" to listOf("👍", "✅"),
        "thumbsdown" to listOf("👎", "❌"),
        "pray" to listOf("🙏", "🤲", "📿"),
        "shrug" to listOf("🤷", "😐"),
        "facepalm" to listOf("🤦", "😑"),
        "think" to listOf("🤔", "💭", "🧠"),
        "idea" to listOf("💡", "🧠", "✨"),
        "strong" to listOf("💪", "🏋️", "✊"),
        "run" to listOf("🏃", "💨"),
        "walk" to listOf("🚶", "👣"),
        "write" to listOf("✍️", "📝", "✏️"),
        "read" to listOf("📖", "📚", "🤓"),

        // ===== ENGLISH - Health & Body =====
        "sick" to listOf("🤒", "🤧", "😷"),
        "hot" to listOf("🥵", "🔥", "☀️"),
        "cold" to listOf("🥶", "❄️", "🧊"),
        "sleep" to listOf("😴", "💤", "🛏️"),
        "doctor" to listOf("🏥", "💊", "🩺"),
        "heart" to listOf("❤️", "💕", "💖"),

        // ===== ENGLISH - Nature & Weather =====
        "fire" to listOf("🔥", "🥵"),
        "sun" to listOf("☀️", "🌞", "😎"),
        "rain" to listOf("🌧️", "☔", "💧"),
        "snow" to listOf("❄️", "⛄", "🌨️"),
        "wind" to listOf("🌬️", "💨", "🍃"),
        "storm" to listOf("⛈️", "🌩️", "🌪️"),
        "rainbow" to listOf("🌈", "✨", "🦄"),
        "star" to listOf("⭐", "🌟", "✨"),
        "moon" to listOf("🌙", "🌕", "🌜"),
        "flower" to listOf("🌸", "🌹", "🌷"),
        "tree" to listOf("🌳", "🌲", "🌴"),
        "water" to listOf("💧", "🌊", "🚿"),
        "earth" to listOf("🌍", "🌎", "🌏"),
        "mountain" to listOf("⛰️", "🏔️", "🗻"),
        "ocean" to listOf("🌊", "🐬", "🐳"),
        "beach" to listOf("🏖️", "🌊", "☀️"),

        // ===== ENGLISH - Animals =====
        "dog" to listOf("🐕", "🐶", "🦮"),
        "cat" to listOf("🐈", "🐱", "😺"),
        "bird" to listOf("🐦", "🕊️", "🦅"),
        "fish" to listOf("🐠", "🐬", "🐳"),
        "bear" to listOf("🐻", "🧸"),
        "rabbit" to listOf("🐰", "🐇"),
        "monkey" to listOf("🐵", "🙈"),
        "lion" to listOf("🦁", "👑"),
        "horse" to listOf("🐴", "🏇"),
        "butterfly" to listOf("🦋", "🌸"),
        "bee" to listOf("🐝", "🍯"),
        "snake" to listOf("🐍", "🐢"),
        "turtle" to listOf("🐢", "🌊"),
        "penguin" to listOf("🐧", "❄️"),
        "chicken" to listOf("🐔", "🐣", "🥚"),
        "cow" to listOf("🐮", "🐄"),
        "pig" to listOf("🐷", "🐖"),

        // ===== ENGLISH - Food & Drink =====
        "food" to listOf("🍕", "🍔", "🍟"),
        "pizza" to listOf("🍕", "🧀", "🔥"),
        "burger" to listOf("🍔", "🍟", "🥤"),
        "coffee" to listOf("☕", "🫖"),
        "tea" to listOf("🍵", "🫖", "☕"),
        "cake" to listOf("🎂", "🍰", "🧁"),
        "cookie" to listOf("🍪", "🍫"),
        "chocolate" to listOf("🍫", "🍪", "🍩"),
        "fruit" to listOf("🍎", "🍊", "🍌"),
        "apple" to listOf("🍎", "🍏"),
        "banana" to listOf("🍌", "🐒"),
        "bread" to listOf("🍞", "🥖", "🥯"),
        "cheese" to listOf("🧀", "🍕"),
        "egg" to listOf("🥚", "🍳"),
        "salad" to listOf("🥗", "🥒", "🥑"),
        "ice cream" to listOf("🍦", "🧊"),
        "candy" to listOf("🍬", "🍭", "🍫"),
        "breakfast" to listOf("🍳", "🥐", "☕"),
        "lunch" to listOf("🍽️", "🥗", "🍕"),
        "dinner" to listOf("🍽️", "🍝", "🥘"),
        "hungry" to listOf("🤤", "🍽️", "😋"),

        // ===== ENGLISH - Celebration & Events =====
        "party" to listOf("🎉", "🥳", "🎊"),
        "birthday" to listOf("🎂", "🎁", "🎈"),
        "gift" to listOf("🎁", "🎀", "🎊"),
        "celebrate" to listOf("🎉", "🥳", "🎊"),
        "holiday" to listOf("🎉", "🏖️", "✈️"),
        "wedding" to listOf("💒", "💍", "👰"),
        "trophy" to listOf("🏆", "🥇", "🎉"),
        "win" to listOf("🏆", "🥇", "🎉"),
        "medal" to listOf("🥇", "🏅", "🏆"),

        // ===== ENGLISH - Objects & Tools =====
        "phone" to listOf("📱", "☎️", "📞"),
        "computer" to listOf("💻", "🖥️", "⌨️"),
        "book" to listOf("📚", "📖", "📕"),
        "money" to listOf("💰", "💵", "🤑"),
        "time" to listOf("⏰", "🕐", "⌛"),
        "clock" to listOf("⏰", "🕐", "⌚"),
        "key" to listOf("🔑", "🔐", "🔒"),
        "camera" to listOf("📷", "📸", "📹"),
        "music" to listOf("🎵", "🎶", "🎸"),
        "bell" to listOf("🔔", "🛎️"),
        "mail" to listOf("📧", "📬", "✉️"),
        "email" to listOf("📧", "📬", "✉️"),
        "pen" to listOf("🖊️", "✏️", "📝"),
        "calendar" to listOf("📅", "📆"),
        "light" to listOf("💡", "🔦", "✨"),
        "tool" to listOf("🔧", "🔨", "🛠️"),
        "scissors" to listOf("✂️", "📐"),
        "bag" to listOf("👜", "🎒", "💼"),
        "box" to listOf("📦", "🗃️"),

        // ===== ENGLISH - Places & Transport =====
        "home" to listOf("🏠", "🏡", "🏘️"),
        "work" to listOf("💼", "🏢", "💪"),
        "school" to listOf("🏫", "📚", "✏️"),
        "hospital" to listOf("🏥", "🚑", "💊"),
        "car" to listOf("🚗", "🚙", "🏎️"),
        "bus" to listOf("🚌", "🚏", "🚎"),
        "plane" to listOf("✈️", "🛫", "🛬"),
        "train" to listOf("🚂", "🚃", "🚄"),
        "boat" to listOf("⛵", "🚢", "🛳️"),
        "rocket" to listOf("🚀", "🌟", "✨"),
        "bicycle" to listOf("🚲", "🚴"),
        "map" to listOf("🗺️", "📍", "🧭"),

        // ===== ENGLISH - Symbols & Misc =====
        "good" to listOf("👍", "✅", "😊"),
        "bad" to listOf("👎", "❌", "😬"),
        "perfect" to listOf("💯", "✅", "👌"),
        "important" to listOf("❗", "⚠️", "📌"),
        "question" to listOf("❓", "🤔", "❔"),
        "check" to listOf("✅", "☑️", "✔️"),
        "warning" to listOf("⚠️", "❗", "🚨"),
        "stop" to listOf("🛑", "❌", "🚫"),
        "new" to listOf("🆕", "✨", "🌟"),
        "100" to listOf("💯", "🔥", "✅"),
        "info" to listOf("ℹ️", "📋", "📊"),
        "up" to listOf("⬆️", "👆", "🔝"),
        "down" to listOf("⬇️", "👇", "📉"),
        "left" to listOf("⬅️", "👈"),
        "right" to listOf("➡️", "👉"),
        "sparkle" to listOf("✨", "🌟", "💫"),
        "magic" to listOf("✨", "🌟", "💫"),
        "luck" to listOf("🍀", "⭐", "🎉"),
        "peace" to listOf("✌️", "🕊️", "☮️"),
        "family" to listOf("👨‍👩‍👦", "👨‍👩‍👧", "❤️"),
        "baby" to listOf("👶", "🍼", "👣"),
        "boy" to listOf("👦", "🧒"),
        "girl" to listOf("👧", "🧒"),
        "man" to listOf("👨", "🧔"),
        "woman" to listOf("👩", "👱‍♀️"),
        "people" to listOf("👥", "🧑‍🤝‍🧑"),
        "sport" to listOf("⚽", "🏀", "🎾"),
        "soccer" to listOf("⚽", "🥅"),
        "basketball" to listOf("🏀", "🏆"),
        "tennis" to listOf("🎾", "🏆"),
        "puzzle" to listOf("🧩", "🤔"),
        "art" to listOf("🎨", "🖌️", "🖼️"),
        "paint" to listOf("🎨", "🖌️"),
        "world" to listOf("🌍", "🌎", "🌏"),

        // ===== HEBREW =====
        "שלום" to listOf("👋", "🙏", "✌️"),
        "אהבה" to listOf("❤️", "😍", "💕"),
        "שמח" to listOf("😊", "😄", "🙂"),
        "שמחה" to listOf("😊", "😄", "🎉"),
        "עצוב" to listOf("😢", "😞", "😔"),
        "תודה" to listOf("🙏", "❤️", "😊"),
        "מזל" to listOf("🍀", "⭐", "🎉"),
        "טוב" to listOf("👍", "✅", "😊"),
        "רע" to listOf("👎", "❌", "😬"),
        "כעס" to listOf("😠", "😡"),
        "כועס" to listOf("😠", "😡"),
        "אוכל" to listOf("🍕", "🍔", "🍟"),
        "בית" to listOf("🏠", "🏡"),
        "ילד" to listOf("👶", "👦", "👧"),
        "ילדה" to listOf("👧", "🧒"),
        "חג" to listOf("🎉", "🥳", "🎊"),
        "שבת" to listOf("🕯️", "✡️", "🙏"),
        "תפילה" to listOf("🙏", "🤲", "🕍"),
        "ספר" to listOf("📚", "📖", "📕"),
        "כסף" to listOf("💰", "💵", "🤑"),
        "מים" to listOf("💧", "🌊", "🚰"),
        "שמש" to listOf("☀️", "🌞", "😎"),
        "גשם" to listOf("🌧️", "☔", "💧"),
        "לב" to listOf("❤️", "💕", "💖"),
        "כוכב" to listOf("⭐", "🌟", "✨"),
        "פרח" to listOf("🌸", "🌹", "🌷"),
        "עץ" to listOf("🌳", "🌲"),
        "כלב" to listOf("🐕", "🐶"),
        "חתול" to listOf("🐈", "🐱"),
        "ציפור" to listOf("🐦", "🕊️"),
        "דג" to listOf("🐠", "🐟"),
        "משפחה" to listOf("👨‍👩‍👦", "👨‍👩‍👧", "❤️"),
        "חבר" to listOf("🤝", "😊", "👋"),
        "חברה" to listOf("🤝", "😊", "👋"),
        "עבודה" to listOf("💼", "🏢", "💪"),
        "בית ספר" to listOf("🏫", "📚", "✏️"),
        "רופא" to listOf("🏥", "💊", "🩺"),
        "מכונית" to listOf("🚗", "🚙"),
        "אוטובוס" to listOf("🚌", "🚏"),
        "מטוס" to listOf("✈️", "🛫"),
        "יום" to listOf("☀️", "🌅"),
        "לילה" to listOf("🌙", "🌃", "💤"),
        "בוקר" to listOf("🌅", "☀️", "☕"),
        "ערב" to listOf("🌆", "🌙"),
        "חם" to listOf("🥵", "🔥", "☀️"),
        "קר" to listOf("🥶", "❄️", "🧊"),
        "יפה" to listOf("😍", "✨", "🌹"),
        "גדול" to listOf("💪", "🏆"),
        "קטן" to listOf("🤏", "🐣"),
        "חדש" to listOf("🆕", "✨"),
        "ישן" to listOf("😴", "💤"),
        "מהר" to listOf("🏃", "💨", "⚡"),
        "אש" to listOf("🔥", "🚒"),
        "ארוחה" to listOf("🍽️", "🍕", "🍔"),
        "עוגה" to listOf("🎂", "🍰"),
        "קפה" to listOf("☕", "🫖"),
        "מתנה" to listOf("🎁", "🎀"),
        "מסיבה" to listOf("🎉", "🥳", "🎊"),
        "יום הולדת" to listOf("🎂", "🎁", "🎈"),
        "סליחה" to listOf("😔", "🙏", "😢"),
        "בבקשה" to listOf("🙏", "🥺"),
        "כן" to listOf("✅", "👍", "🙌"),
        "לא" to listOf("❌", "👎", "🚫"),
        "מוסיקה" to listOf("🎵", "🎶", "🎸"),
        "ספורט" to listOf("⚽", "🏀", "🎾"),
        "כדורגל" to listOf("⚽", "🥅"),
        "כדורסל" to listOf("🏀", "🏆"),
        "ניצחון" to listOf("🏆", "🥇", "🎉"),
        "חכם" to listOf("🧠", "🤓", "💡"),
        "חזק" to listOf("💪", "🏋️"),
        "שקט" to listOf("🤫", "🤐"),
        "רעש" to listOf("📢", "🔔", "🗣️"),
        "תורה" to listOf("📜", "✡️", "📖"),
        "ישראל" to listOf("🇮🇱", "✡️", "🕍"),
        "ירושלים" to listOf("🕍", "✡️", "🇮🇱")
    )

    /**
     * Predict emoji for a given word.
     * @param word The typed word to match against keywords.
     * @param language The current language code (unused for now, keywords handle both).
     * @return Up to 3 emoji suggestions, filtered through kosher filter if available.
     */
    fun predict(word: String, language: String): List<String> {
        if (word.isBlank()) return emptyList()

        val key = word.lowercase().trim()
        val emojis = keywordMap[key] ?: return emptyList()

        val filtered = if (kosherFilter != null) {
            emojis.filter { !kosherFilter.isBlocked(it) }
        } else {
            emojis
        }

        return filtered.take(3)
    }
}
