package com.megalife.ime.feature

/**
 * Curated kosher emoji dataset.
 * Excluded: suggestive, violent, alcohol, inappropriate content.
 * Organized by category with names for search.
 */
object EmojiData {

    data class Emoji(
        val emoji: String,
        val name: String,
        val category: EmojiCategory,
        val hasSkinTone: Boolean = false
    )

    enum class EmojiCategory(val displayName: String, val icon: String) {
        RECENT("Recent", "🕐"),
        SMILEYS("Smileys", "😊"),
        PEOPLE("People", "👋"),
        NATURE("Nature", "🌿"),
        FOOD("Food", "🍎"),
        TRAVEL("Travel", "✈️"),
        OBJECTS("Objects", "💡"),
        SYMBOLS("Symbols", "❤️")
    }

    /** Skin tone modifiers */
    val skinTones = listOf(
        "",           // default yellow
        "\uD83C\uDFFB", // light
        "\uD83C\uDFFC", // medium-light
        "\uD83C\uDFFD", // medium
        "\uD83C\uDFFE", // medium-dark
        "\uD83C\uDFFF"  // dark
    )

    /** Apply skin tone to an emoji that supports it */
    fun applySkinTone(emoji: String, toneIndex: Int): String {
        if (toneIndex <= 0 || toneIndex >= skinTones.size) return emoji
        // Insert skin tone modifier after first code point
        val firstCodePoint = emoji.codePointAt(0)
        val charCount = Character.charCount(firstCodePoint)
        return emoji.substring(0, charCount) + skinTones[toneIndex] + emoji.substring(charCount)
    }

    val allEmojis: List<Emoji> = buildList {
        // ===== SMILEYS =====
        add(Emoji("😀", "grinning face", EmojiCategory.SMILEYS))
        add(Emoji("😃", "grinning face with big eyes", EmojiCategory.SMILEYS))
        add(Emoji("😄", "grinning face with smiling eyes", EmojiCategory.SMILEYS))
        add(Emoji("😁", "beaming face", EmojiCategory.SMILEYS))
        add(Emoji("😊", "smiling face with smiling eyes", EmojiCategory.SMILEYS))
        add(Emoji("😇", "smiling face with halo", EmojiCategory.SMILEYS))
        add(Emoji("🙂", "slightly smiling face", EmojiCategory.SMILEYS))
        add(Emoji("😉", "winking face", EmojiCategory.SMILEYS))
        add(Emoji("😌", "relieved face", EmojiCategory.SMILEYS))
        add(Emoji("😍", "smiling face with heart-eyes", EmojiCategory.SMILEYS))
        add(Emoji("😂", "face with tears of joy", EmojiCategory.SMILEYS))
        add(Emoji("🤣", "rolling on the floor laughing", EmojiCategory.SMILEYS))
        add(Emoji("😅", "grinning face with sweat", EmojiCategory.SMILEYS))
        add(Emoji("😆", "grinning squinting face", EmojiCategory.SMILEYS))
        add(Emoji("😋", "face savoring food", EmojiCategory.SMILEYS))
        add(Emoji("😎", "smiling face with sunglasses", EmojiCategory.SMILEYS))
        add(Emoji("🤩", "star-struck", EmojiCategory.SMILEYS))
        add(Emoji("🤗", "hugging face", EmojiCategory.SMILEYS))
        add(Emoji("🤔", "thinking face", EmojiCategory.SMILEYS))
        add(Emoji("🤐", "zipper-mouth face", EmojiCategory.SMILEYS))
        add(Emoji("😐", "neutral face", EmojiCategory.SMILEYS))
        add(Emoji("😑", "expressionless face", EmojiCategory.SMILEYS))
        add(Emoji("😶", "face without mouth", EmojiCategory.SMILEYS))
        add(Emoji("😏", "smirking face", EmojiCategory.SMILEYS))
        add(Emoji("😒", "unamused face", EmojiCategory.SMILEYS))
        add(Emoji("🙄", "face with rolling eyes", EmojiCategory.SMILEYS))
        add(Emoji("😬", "grimacing face", EmojiCategory.SMILEYS))
        add(Emoji("😔", "pensive face", EmojiCategory.SMILEYS))
        add(Emoji("😪", "sleepy face", EmojiCategory.SMILEYS))
        add(Emoji("😴", "sleeping face", EmojiCategory.SMILEYS))
        add(Emoji("🤤", "drooling face", EmojiCategory.SMILEYS))
        add(Emoji("😷", "face with medical mask", EmojiCategory.SMILEYS))
        add(Emoji("🤒", "face with thermometer", EmojiCategory.SMILEYS))
        add(Emoji("🤕", "face with head-bandage", EmojiCategory.SMILEYS))
        add(Emoji("😵", "face with crossed-out eyes", EmojiCategory.SMILEYS))
        add(Emoji("🥴", "woozy face", EmojiCategory.SMILEYS))
        add(Emoji("😲", "astonished face", EmojiCategory.SMILEYS))
        add(Emoji("😳", "flushed face", EmojiCategory.SMILEYS))
        add(Emoji("🥺", "pleading face", EmojiCategory.SMILEYS))
        add(Emoji("😢", "crying face", EmojiCategory.SMILEYS))
        add(Emoji("😭", "loudly crying face", EmojiCategory.SMILEYS))
        add(Emoji("😤", "face with steam from nose", EmojiCategory.SMILEYS))
        add(Emoji("😠", "angry face", EmojiCategory.SMILEYS))
        add(Emoji("🥱", "yawning face", EmojiCategory.SMILEYS))
        add(Emoji("😮", "face with open mouth", EmojiCategory.SMILEYS))
        add(Emoji("😯", "hushed face", EmojiCategory.SMILEYS))
        add(Emoji("😧", "anguished face", EmojiCategory.SMILEYS))
        add(Emoji("🤓", "nerd face", EmojiCategory.SMILEYS))
        add(Emoji("🧐", "face with monocle", EmojiCategory.SMILEYS))
        add(Emoji("🤷", "person shrugging", EmojiCategory.SMILEYS, hasSkinTone = true))
        add(Emoji("🤦", "person facepalming", EmojiCategory.SMILEYS, hasSkinTone = true))

        // ===== PEOPLE & GESTURES =====
        add(Emoji("👋", "waving hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("🤚", "raised back of hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("✋", "raised hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("🖐️", "hand with fingers splayed", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👌", "OK hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("✌️", "victory hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👍", "thumbs up", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👎", "thumbs down", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👏", "clapping hands", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("🙌", "raising hands", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("🤝", "handshake", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("🙏", "folded hands", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("✍️", "writing hand", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("💪", "flexed biceps", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("☝️", "index pointing up", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👆", "backhand index pointing up", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👇", "backhand index pointing down", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👈", "backhand index pointing left", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👉", "backhand index pointing right", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👶", "baby", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👦", "boy", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👧", "girl", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👨", "man", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👩", "woman", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👴", "old man", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👵", "old woman", EmojiCategory.PEOPLE, hasSkinTone = true))
        add(Emoji("👨\u200D👩\u200D👦", "family man woman boy", EmojiCategory.PEOPLE))
        add(Emoji("👨\u200D👩\u200D👧", "family man woman girl", EmojiCategory.PEOPLE))
        add(Emoji("👨\u200D👩\u200D👦\u200D👦", "family man woman boy boy", EmojiCategory.PEOPLE))
        add(Emoji("👨\u200D👩\u200D👧\u200D👦", "family man woman girl boy", EmojiCategory.PEOPLE))

        // ===== NATURE =====
        add(Emoji("🐶", "dog face", EmojiCategory.NATURE))
        add(Emoji("🐱", "cat face", EmojiCategory.NATURE))
        add(Emoji("🐭", "mouse face", EmojiCategory.NATURE))
        add(Emoji("🐹", "hamster", EmojiCategory.NATURE))
        add(Emoji("🐰", "rabbit face", EmojiCategory.NATURE))
        add(Emoji("🦊", "fox face", EmojiCategory.NATURE))
        add(Emoji("🐻", "bear face", EmojiCategory.NATURE))
        add(Emoji("🐼", "panda face", EmojiCategory.NATURE))
        add(Emoji("🐨", "koala", EmojiCategory.NATURE))
        add(Emoji("🐯", "tiger face", EmojiCategory.NATURE))
        add(Emoji("🦁", "lion face", EmojiCategory.NATURE))
        add(Emoji("🐮", "cow face", EmojiCategory.NATURE))
        add(Emoji("🐷", "pig face", EmojiCategory.NATURE))
        add(Emoji("🐸", "frog face", EmojiCategory.NATURE))
        add(Emoji("🐵", "monkey face", EmojiCategory.NATURE))
        add(Emoji("🐔", "chicken", EmojiCategory.NATURE))
        add(Emoji("🐧", "penguin", EmojiCategory.NATURE))
        add(Emoji("🐦", "bird", EmojiCategory.NATURE))
        add(Emoji("🦅", "eagle", EmojiCategory.NATURE))
        add(Emoji("🦋", "butterfly", EmojiCategory.NATURE))
        add(Emoji("🐛", "bug", EmojiCategory.NATURE))
        add(Emoji("🐝", "honeybee", EmojiCategory.NATURE))
        add(Emoji("🐠", "tropical fish", EmojiCategory.NATURE))
        add(Emoji("🐬", "dolphin", EmojiCategory.NATURE))
        add(Emoji("🐳", "spouting whale", EmojiCategory.NATURE))
        add(Emoji("🐢", "turtle", EmojiCategory.NATURE))
        add(Emoji("🐍", "snake", EmojiCategory.NATURE))
        add(Emoji("🦎", "lizard", EmojiCategory.NATURE))
        add(Emoji("🕊️", "dove", EmojiCategory.NATURE))
        add(Emoji("🌸", "cherry blossom", EmojiCategory.NATURE))
        add(Emoji("🌹", "rose", EmojiCategory.NATURE))
        add(Emoji("🌻", "sunflower", EmojiCategory.NATURE))
        add(Emoji("🌺", "hibiscus", EmojiCategory.NATURE))
        add(Emoji("🌷", "tulip", EmojiCategory.NATURE))
        add(Emoji("🌱", "seedling", EmojiCategory.NATURE))
        add(Emoji("🌲", "evergreen tree", EmojiCategory.NATURE))
        add(Emoji("🌳", "deciduous tree", EmojiCategory.NATURE))
        add(Emoji("🌴", "palm tree", EmojiCategory.NATURE))
        add(Emoji("🍀", "four leaf clover", EmojiCategory.NATURE))
        add(Emoji("🍁", "maple leaf", EmojiCategory.NATURE))
        add(Emoji("🍂", "fallen leaf", EmojiCategory.NATURE))
        add(Emoji("🌈", "rainbow", EmojiCategory.NATURE))
        add(Emoji("☀️", "sun", EmojiCategory.NATURE))
        add(Emoji("🌤️", "sun behind small cloud", EmojiCategory.NATURE))
        add(Emoji("⛅", "sun behind cloud", EmojiCategory.NATURE))
        add(Emoji("🌧️", "cloud with rain", EmojiCategory.NATURE))
        add(Emoji("❄️", "snowflake", EmojiCategory.NATURE))
        add(Emoji("⛄", "snowman", EmojiCategory.NATURE))
        add(Emoji("🌊", "water wave", EmojiCategory.NATURE))
        add(Emoji("🌙", "crescent moon", EmojiCategory.NATURE))
        add(Emoji("⭐", "star", EmojiCategory.NATURE))
        add(Emoji("🌟", "glowing star", EmojiCategory.NATURE))
        add(Emoji("✨", "sparkles", EmojiCategory.NATURE))
        add(Emoji("🔥", "fire", EmojiCategory.NATURE))

        // ===== FOOD =====
        add(Emoji("🍎", "red apple", EmojiCategory.FOOD))
        add(Emoji("🍊", "tangerine", EmojiCategory.FOOD))
        add(Emoji("🍋", "lemon", EmojiCategory.FOOD))
        add(Emoji("🍌", "banana", EmojiCategory.FOOD))
        add(Emoji("🍉", "watermelon", EmojiCategory.FOOD))
        add(Emoji("🍇", "grapes", EmojiCategory.FOOD))
        add(Emoji("🍓", "strawberry", EmojiCategory.FOOD))
        add(Emoji("🍑", "peach", EmojiCategory.FOOD))
        add(Emoji("🍒", "cherries", EmojiCategory.FOOD))
        add(Emoji("🥝", "kiwi fruit", EmojiCategory.FOOD))
        add(Emoji("🍅", "tomato", EmojiCategory.FOOD))
        add(Emoji("🥑", "avocado", EmojiCategory.FOOD))
        add(Emoji("🥕", "carrot", EmojiCategory.FOOD))
        add(Emoji("🌽", "corn", EmojiCategory.FOOD))
        add(Emoji("🥦", "broccoli", EmojiCategory.FOOD))
        add(Emoji("🥒", "cucumber", EmojiCategory.FOOD))
        add(Emoji("🍞", "bread", EmojiCategory.FOOD))
        add(Emoji("🥖", "baguette bread", EmojiCategory.FOOD))
        add(Emoji("🥯", "bagel", EmojiCategory.FOOD))
        add(Emoji("🧀", "cheese wedge", EmojiCategory.FOOD))
        add(Emoji("🥚", "egg", EmojiCategory.FOOD))
        add(Emoji("🍳", "cooking", EmojiCategory.FOOD))
        add(Emoji("🥗", "green salad", EmojiCategory.FOOD))
        add(Emoji("🍕", "pizza", EmojiCategory.FOOD))
        add(Emoji("🍔", "hamburger", EmojiCategory.FOOD))
        add(Emoji("🍟", "french fries", EmojiCategory.FOOD))
        add(Emoji("🌮", "taco", EmojiCategory.FOOD))
        add(Emoji("🍝", "spaghetti", EmojiCategory.FOOD))
        add(Emoji("🍜", "steaming bowl", EmojiCategory.FOOD))
        add(Emoji("🍣", "sushi", EmojiCategory.FOOD))
        add(Emoji("🍰", "shortcake", EmojiCategory.FOOD))
        add(Emoji("🎂", "birthday cake", EmojiCategory.FOOD))
        add(Emoji("🍪", "cookie", EmojiCategory.FOOD))
        add(Emoji("🍫", "chocolate bar", EmojiCategory.FOOD))
        add(Emoji("🍬", "candy", EmojiCategory.FOOD))
        add(Emoji("🍭", "lollipop", EmojiCategory.FOOD))
        add(Emoji("🍩", "doughnut", EmojiCategory.FOOD))
        add(Emoji("🍦", "soft ice cream", EmojiCategory.FOOD))
        add(Emoji("☕", "hot beverage", EmojiCategory.FOOD))
        add(Emoji("🍵", "teacup", EmojiCategory.FOOD))
        add(Emoji("🧃", "beverage box", EmojiCategory.FOOD))
        add(Emoji("🥤", "cup with straw", EmojiCategory.FOOD))
        add(Emoji("🧊", "ice", EmojiCategory.FOOD))
        // Note: alcohol emojis (🍺🍷🍸🍹🥂🍾) excluded for kosher compliance

        // ===== TRAVEL =====
        add(Emoji("🚗", "automobile", EmojiCategory.TRAVEL))
        add(Emoji("🚕", "taxi", EmojiCategory.TRAVEL))
        add(Emoji("🚌", "bus", EmojiCategory.TRAVEL))
        add(Emoji("🚎", "trolleybus", EmojiCategory.TRAVEL))
        add(Emoji("🚑", "ambulance", EmojiCategory.TRAVEL))
        add(Emoji("🚒", "fire engine", EmojiCategory.TRAVEL))
        add(Emoji("🚲", "bicycle", EmojiCategory.TRAVEL))
        add(Emoji("✈️", "airplane", EmojiCategory.TRAVEL))
        add(Emoji("🚀", "rocket", EmojiCategory.TRAVEL))
        add(Emoji("🚂", "locomotive", EmojiCategory.TRAVEL))
        add(Emoji("🚃", "railway car", EmojiCategory.TRAVEL))
        add(Emoji("⛵", "sailboat", EmojiCategory.TRAVEL))
        add(Emoji("🚢", "ship", EmojiCategory.TRAVEL))
        add(Emoji("🏠", "house", EmojiCategory.TRAVEL))
        add(Emoji("🏡", "house with garden", EmojiCategory.TRAVEL))
        add(Emoji("🏫", "school", EmojiCategory.TRAVEL))
        add(Emoji("🏥", "hospital", EmojiCategory.TRAVEL))
        add(Emoji("🏪", "convenience store", EmojiCategory.TRAVEL))
        add(Emoji("⛪", "church", EmojiCategory.TRAVEL))
        add(Emoji("🕍", "synagogue", EmojiCategory.TRAVEL))
        add(Emoji("🏔️", "snow-capped mountain", EmojiCategory.TRAVEL))
        add(Emoji("⛰️", "mountain", EmojiCategory.TRAVEL))
        add(Emoji("🏖️", "beach", EmojiCategory.TRAVEL))
        add(Emoji("🏕️", "camping", EmojiCategory.TRAVEL))
        add(Emoji("🗺️", "world map", EmojiCategory.TRAVEL))
        add(Emoji("🌍", "globe europe-africa", EmojiCategory.TRAVEL))
        add(Emoji("🌎", "globe americas", EmojiCategory.TRAVEL))
        add(Emoji("🌏", "globe asia-australia", EmojiCategory.TRAVEL))

        // ===== OBJECTS =====
        add(Emoji("📱", "mobile phone", EmojiCategory.OBJECTS))
        add(Emoji("💻", "laptop", EmojiCategory.OBJECTS))
        add(Emoji("⌨️", "keyboard", EmojiCategory.OBJECTS))
        add(Emoji("📷", "camera", EmojiCategory.OBJECTS))
        add(Emoji("📞", "telephone receiver", EmojiCategory.OBJECTS))
        add(Emoji("📺", "television", EmojiCategory.OBJECTS))
        add(Emoji("🔔", "bell", EmojiCategory.OBJECTS))
        add(Emoji("📢", "loudspeaker", EmojiCategory.OBJECTS))
        add(Emoji("🎵", "musical note", EmojiCategory.OBJECTS))
        add(Emoji("🎶", "musical notes", EmojiCategory.OBJECTS))
        add(Emoji("🎤", "microphone", EmojiCategory.OBJECTS))
        add(Emoji("🎧", "headphone", EmojiCategory.OBJECTS))
        add(Emoji("📚", "books", EmojiCategory.OBJECTS))
        add(Emoji("📖", "open book", EmojiCategory.OBJECTS))
        add(Emoji("📝", "memo", EmojiCategory.OBJECTS))
        add(Emoji("✏️", "pencil", EmojiCategory.OBJECTS))
        add(Emoji("📎", "paperclip", EmojiCategory.OBJECTS))
        add(Emoji("📌", "pushpin", EmojiCategory.OBJECTS))
        add(Emoji("📅", "calendar", EmojiCategory.OBJECTS))
        add(Emoji("📆", "tear-off calendar", EmojiCategory.OBJECTS))
        add(Emoji("🕐", "one o'clock", EmojiCategory.OBJECTS))
        add(Emoji("⏰", "alarm clock", EmojiCategory.OBJECTS))
        add(Emoji("⏳", "hourglass", EmojiCategory.OBJECTS))
        add(Emoji("🔑", "key", EmojiCategory.OBJECTS))
        add(Emoji("🔒", "locked", EmojiCategory.OBJECTS))
        add(Emoji("🔓", "unlocked", EmojiCategory.OBJECTS))
        add(Emoji("💡", "light bulb", EmojiCategory.OBJECTS))
        add(Emoji("🔦", "flashlight", EmojiCategory.OBJECTS))
        add(Emoji("🔧", "wrench", EmojiCategory.OBJECTS))
        add(Emoji("🔨", "hammer", EmojiCategory.OBJECTS))
        add(Emoji("✂️", "scissors", EmojiCategory.OBJECTS))
        add(Emoji("📦", "package", EmojiCategory.OBJECTS))
        add(Emoji("📬", "open mailbox", EmojiCategory.OBJECTS))
        add(Emoji("📧", "e-mail", EmojiCategory.OBJECTS))
        add(Emoji("💰", "money bag", EmojiCategory.OBJECTS))
        add(Emoji("💳", "credit card", EmojiCategory.OBJECTS))
        add(Emoji("🎁", "wrapped gift", EmojiCategory.OBJECTS))
        add(Emoji("🎈", "balloon", EmojiCategory.OBJECTS))
        add(Emoji("🎉", "party popper", EmojiCategory.OBJECTS))
        add(Emoji("🎊", "confetti ball", EmojiCategory.OBJECTS))
        add(Emoji("🏆", "trophy", EmojiCategory.OBJECTS))
        add(Emoji("🥇", "first place medal", EmojiCategory.OBJECTS))
        add(Emoji("⚽", "soccer ball", EmojiCategory.OBJECTS))
        add(Emoji("🏀", "basketball", EmojiCategory.OBJECTS))
        add(Emoji("🎾", "tennis", EmojiCategory.OBJECTS))
        add(Emoji("🎯", "direct hit", EmojiCategory.OBJECTS))
        add(Emoji("🧩", "puzzle piece", EmojiCategory.OBJECTS))
        add(Emoji("🎨", "artist palette", EmojiCategory.OBJECTS))
        add(Emoji("🕎", "menorah", EmojiCategory.OBJECTS))
        add(Emoji("✡️", "star of david", EmojiCategory.OBJECTS))
        add(Emoji("🛒", "shopping cart", EmojiCategory.OBJECTS))
        add(Emoji("💊", "pill", EmojiCategory.OBJECTS))

        // ===== SYMBOLS =====
        add(Emoji("❤️", "red heart", EmojiCategory.SYMBOLS))
        add(Emoji("🧡", "orange heart", EmojiCategory.SYMBOLS))
        add(Emoji("💛", "yellow heart", EmojiCategory.SYMBOLS))
        add(Emoji("💚", "green heart", EmojiCategory.SYMBOLS))
        add(Emoji("💙", "blue heart", EmojiCategory.SYMBOLS))
        add(Emoji("💜", "purple heart", EmojiCategory.SYMBOLS))
        add(Emoji("🖤", "black heart", EmojiCategory.SYMBOLS))
        add(Emoji("🤍", "white heart", EmojiCategory.SYMBOLS))
        add(Emoji("💯", "hundred points", EmojiCategory.SYMBOLS))
        add(Emoji("💢", "anger symbol", EmojiCategory.SYMBOLS))
        add(Emoji("💬", "speech balloon", EmojiCategory.SYMBOLS))
        add(Emoji("💭", "thought balloon", EmojiCategory.SYMBOLS))
        add(Emoji("❗", "exclamation mark", EmojiCategory.SYMBOLS))
        add(Emoji("❓", "question mark", EmojiCategory.SYMBOLS))
        add(Emoji("❕", "white exclamation mark", EmojiCategory.SYMBOLS))
        add(Emoji("❔", "white question mark", EmojiCategory.SYMBOLS))
        add(Emoji("✅", "check mark", EmojiCategory.SYMBOLS))
        add(Emoji("❌", "cross mark", EmojiCategory.SYMBOLS))
        add(Emoji("⭕", "hollow red circle", EmojiCategory.SYMBOLS))
        add(Emoji("➕", "plus", EmojiCategory.SYMBOLS))
        add(Emoji("➖", "minus", EmojiCategory.SYMBOLS))
        add(Emoji("➗", "divide", EmojiCategory.SYMBOLS))
        add(Emoji("✖️", "multiply", EmojiCategory.SYMBOLS))
        add(Emoji("♾️", "infinity", EmojiCategory.SYMBOLS))
        add(Emoji("⬆️", "up arrow", EmojiCategory.SYMBOLS))
        add(Emoji("⬇️", "down arrow", EmojiCategory.SYMBOLS))
        add(Emoji("⬅️", "left arrow", EmojiCategory.SYMBOLS))
        add(Emoji("➡️", "right arrow", EmojiCategory.SYMBOLS))
        add(Emoji("↩️", "right arrow curving left", EmojiCategory.SYMBOLS))
        add(Emoji("↪️", "left arrow curving right", EmojiCategory.SYMBOLS))
        add(Emoji("🔄", "counterclockwise arrows", EmojiCategory.SYMBOLS))
        add(Emoji("ℹ️", "information", EmojiCategory.SYMBOLS))
        add(Emoji("🔴", "red circle", EmojiCategory.SYMBOLS))
        add(Emoji("🟢", "green circle", EmojiCategory.SYMBOLS))
        add(Emoji("🔵", "blue circle", EmojiCategory.SYMBOLS))
        add(Emoji("⚪", "white circle", EmojiCategory.SYMBOLS))
        add(Emoji("⚫", "black circle", EmojiCategory.SYMBOLS))
        add(Emoji("🟥", "red square", EmojiCategory.SYMBOLS))
        add(Emoji("🟩", "green square", EmojiCategory.SYMBOLS))
        add(Emoji("🟦", "blue square", EmojiCategory.SYMBOLS))
        add(Emoji("⬛", "black large square", EmojiCategory.SYMBOLS))
        add(Emoji("⬜", "white large square", EmojiCategory.SYMBOLS))
    }

    /** Search emoji by name */
    fun search(query: String): List<Emoji> {
        if (query.isBlank()) return emptyList()
        val lower = query.lowercase()
        return allEmojis.filter { it.name.contains(lower) }
    }

    /** Get emoji by category */
    fun getByCategory(category: EmojiCategory): List<Emoji> {
        return allEmojis.filter { it.category == category }
    }
}
